[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
runner = [
  "qemu-system-riscv64",
  "-machine", "virt",
  "-bios", "none",
  "-nographic",
  "-serial", "mon:stdio",
  "-kernel"
]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.ld",
  "-C", "target-feature=+zicsr"
]