[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -M virt -bios default -nographic -serial mon:stdio -kernel"
rustflags = [
  "-C", "link-arg=-Tlink.ld",
]