[build]
# Your bare-metal RISC-V target
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
# Run ELF directly in QEMU when you `cargo run`
runner = [
  "qemu-system-riscv64",
  "-machine", "virt",
  "-bios", "none",
  "-nographic",
  "-serial", "mon:stdio",
  "-kernel"
]

# Linker script + Zicsr feature (the target triple already implies IMAC)
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.ld",
  "-C", "target-feature=+zicsr"
]